# Generated by Django 5.2.17 on 2026-09-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('ref', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=500)),
                ('buyer', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=3)),
                ('cpv', models.CharField(blank=True, max_length=8)),
                ('nature', models.CharField(blank=True, max_length=20)),
                ('published', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('sector', models.CharField(blank=True, max_length=40)),
                ('sector_source', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['published'], name='tenders_ten_publish_60231b_idx'), models.Index(fields=['sector'], name='tenders_ten_sector_8a6a67_idx'), models.Index(fields=['country'], name='tenders_ten_country_9afac6_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'ref'), name='uniq_source_ref')],
            },
        ),
    ]
